# Generated by Django 4.0.2 on 2022-02-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forummessage',
            old_name='room',
            new_name='forum',
        ),
    ]
